name: sds210-project
channels:
  - conda-forge

dependencies:
  # Core
  - python=3.14          # stable version pinned, conda-forge will resolve compatible versions of the packages below

  # Notebook environment
  - jupyterlab
  - ipykernel

  # To load .env
  - python-dotenv
  
  # Progress bar
  - tqdm

  # Geospatial stack
  - geopandas

  # Interactive maps
  - folium
  - jenkspy
